### ISSUE TITLE
Google Home doesn't see child Fan Light Switch

### ISSUE THREAD

**Issue by kerbs17** [rafaelborja/SmartthingsKingOfFansZigbee#12]
I recently updated the Google Home integration to the latest per https://support.smartthings.com/hc/en-us/articles/360046899371?mc_cid=7feca9070e&mc_eid=fbd6194413#voice and now I don't see the "Fan Light" child switch.  It was there with the old Google Home integration.

I tried removing the "Fan Light" child device, and saw it re-added in SmartThings, yet still was not seeing it in the Google Home app.

**Comment by kerbs17** [comment]
Turns out this is a known shortcoming of the updated Google Home integration, it doesn't support Child Devices.  Sounds like it is in the work though.

https://community.smartthings.com/t/updates-to-google-integration/192849/233

**Comment by rafaelborja** [comment]
Ow! That's a bad news. I will have to wait until smartthings fixes it.


Rafael Borja
rafaelborja@gmail.com

**Comment by rafaelborja** [comment]
Interesting. My google home is recognizing the child device
