### ISSUE TITLE
History Entries

### ISSUE THREAD

**Issue by David-Johns** [rafaelborja/SmartthingsKingOfFansZigbee#2]
So awesome having this work with the new app! Thanks so much!

I'm not sure if the DTH handles this, but the history on the light child device records the status 3-4 times per minute. The fan only records the status of the light dimmer once every 5 minutes. Is there a way to change the DTH to only add to the history changes to the light on/off and dimmer level and changes in fan speed?

**Comment by rafaelborja** [comment]
I'm taking a look on the code. It happens because update/refresh events are being tagged as state change events. Can you you send me a screenshot of those history events?

**Comment by David-Johns** [comment]
Thanks so much for looking at this.
![Screenshot_20200815-202123](https://user-images.githubusercontent.com/66101095/90324502-3e515600-df35-11ea-9b2f-11c0c425bd4c.png)
![Screenshot_20200815-202146](https://user-images.githubusercontent.com/66101095/90324504-41e4dd00-df35-11ea-9bde-9fbfac6c6628.png)

**Comment by rafaelborja** [comment]
Hi


There's a with the fix (v.02). After testing o Merge into master

Feel free to test it

Best regards

**Comment by David-Johns** [comment]
Great progress! The light child device now shows the history properly. However, the fan itself still reports the light's dimmer setting (whether on or off) every 5 minutes. Is there anything that could be done about that? I did update both pieces of code when I updated my device controller.

Thanks for your work on this!

**Comment by rafaelborja** [comment]
You have to update your preferences (due to another fix to change settings)


Rafael Borja
rafaelborja@gmail.com

**Comment by David-Johns** [comment]
Is this in the app or in the web portal? If the app, am I needing to change what the dinner controls to fan? Right now it's set on light. Or do I need to recreate the child device?

If in the web portal, I did already go in to each fan and click "update", but without changing any settings.

**Comment by rafaelborja** [comment]
I just commited a fix for it. No need to change settings.


Rafael Borja
rafaelborja@gmail.com

**Comment by rafaelborja** [comment]
Finally final version committed on branch v.02.

Once it's validated I'll created a tag and update on the comunity

**Comment by David-Johns** [comment]
Rafael,

I'm not sure what I'm doing wrong, but it's still reporting on the dimmer status every 5 minutes in the parent device.

Thanks,
David

**Comment by rafaelborja** [comment]
Can you attach the code you are using for both main and child device?

Have you published after updating?


Rafael Borja
rafaelborja@gmail.com

**Comment by David-Johns** [comment]
Here's the code
[King Of Fans Zigbee Fan Controller.txt](https://github.com/rafaelborja/SmartthingsKingOfFansZigbee/files/5213428/King.Of.Fans.Zigbee.Fan.Controller.txt)
[King Of Fans Zigbee Fan Controller - Light Child Device.txt](https://github.com/rafaelborja/SmartthingsKingOfFansZigbee/files/5213429/King.Of.Fans.Zigbee.Fan.Controller.-.Light.Child.Device.txt)

**Comment by gfa100856** [comment]
Thank you
